# This notebook refines the Excel file of the field data collected by our group, keeping only the necessary information and saving them as an easily accessible .csv file.

In [1]:
import numpy as np
import pandas as pd
import geopandas as gpd

In [2]:
# Set some directories. Here we use absolute directories. 
cwd = 'c:\\Users\\m1865\\Desktop\\Ticino'
cwd_Field = cwd + '\\FieldData'
cwd_Field_Data1 = cwd_Field + '\\Field Dataset 1'
cwd_Field_Data1_CSV = cwd_Field_Data1 + "\\CSV"

### Refinement

In [4]:
df_Field1 = pd.read_excel(cwd_Field_Data1 + '\\Sintesi_siti_ParcoTicino_con_specie.xlsx')
df_Field1.head()

,ESU,Nome ESU Campagna 2,Sito_name,Sampling_date,Field_campaing,Leaf_sampling,Lat,Long,X_UTM (est),Y_UTM (nord),...,Piano Dominato - Acer Campestre,Piano Dominato - Alnus Glutinosa,Piano Dominato - Populus Tremula,Piano Dominato - Quercus Cerris,Piano Dominato - Popolus Nigra,Piano Dominato - Fraxinus Ornus,Piano Dominato - Castanea Sativa Miller,Piano Dominato - Ailanthus Altissima,Piano Dominato - Crataegus Monogyna,Piano Dominato - Copertura
0,FOR01,FOR44,diga,2022-06-14,1,y,45°34.0787',8°42.7080',477510.968,5046089.097,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.8
1,FOR02,FOR45,diga,2022-06-14,1,y,45°34.2126',8°42.7501',477566.636,5046336.872,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
2,FOR03,FOR46,diga,2022-06-14,1,y,45°34.1851',8°42.7864',477613.662,5046285.820,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.7
3,FOR04,FOR40,Bosco cancello,2022-06-16,1,y,45°17.4106',8°56.1672',494990.757,5015188.194,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
4,FOR05,FOR41,Bosco cancello,2022-06-16,1,y,45°17.4494',8°56.3050',495170.934,5015259.820,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0

In [5]:
# Fill NaN with 0 to simplify the later process
df_Field1 = df_Field1.fillna(0)
df_Field1.head()

,ESU,Nome ESU Campagna 2,Sito_name,Sampling_date,Field_campaing,Leaf_sampling,Lat,Long,X_UTM (est),Y_UTM (nord),...,Piano Dominato - Acer Campestre,Piano Dominato - Alnus Glutinosa,Piano Dominato - Populus Tremula,Piano Dominato - Quercus Cerris,Piano Dominato - Popolus Nigra,Piano Dominato - Fraxinus Ornus,Piano Dominato - Castanea Sativa Miller,Piano Dominato - Ailanthus Altissima,Piano Dominato - Crataegus Monogyna,Piano Dominato - Copertura
0,FOR01,FOR44,diga,2022-06-14,1,y,45°34.0787',8°42.7080',477510.968,5046089.097,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.8
1,FOR02,FOR45,diga,2022-06-14,1,y,45°34.2126',8°42.7501',477566.636,5046336.872,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,FOR03,FOR46,diga,2022-06-14,1,y,45°34.1851',8°42.7864',477613.662,5046285.820,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.7
3,FOR04,FOR40,Bosco cancello,2022-06-16,1,y,45°17.4106',8°56.1672',494990.757,5015188.194,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,FOR05,FOR41,Bosco cancello,2022-06-16,1,y,45°17.4494',8°56.3050',495170.934,5015259.820,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
# Convert the default float values to int64 values
df_Field1_Columns = df_Field1.columns
for column in df_Field1_Columns:
    if ("Piano Dominato" in column) or ("Piano Dominante" in column):
        if not ("Copertura" in column):
            df_Field1 = df_Field1.astype({column: 'int64'})
df_Field1.head()

,ESU,Nome ESU Campagna 2,Sito_name,Sampling_date,Field_campaing,Leaf_sampling,Lat,Long,X_UTM (est),Y_UTM (nord),...,Piano Dominato - Acer Campestre,Piano Dominato - Alnus Glutinosa,Piano Dominato - Populus Tremula,Piano Dominato - Quercus Cerris,Piano Dominato - Popolus Nigra,Piano Dominato - Fraxinus Ornus,Piano Dominato - Castanea Sativa Miller,Piano Dominato - Ailanthus Altissima,Piano Dominato - Crataegus Monogyna,Piano Dominato - Copertura
0,FOR01,FOR44,diga,2022-06-14,1,y,45°34.0787',8°42.7080',477510.968,5046089.097,...,0,0,0,0,0,0,0,0,0,0.8
1,FOR02,FOR45,diga,2022-06-14,1,y,45°34.2126',8°42.7501',477566.636,5046336.872,...,0,0,0,0,0,0,0,0,0,1.0
2,FOR03,FOR46,diga,2022-06-14,1,y,45°34.1851',8°42.7864',477613.662,5046285.820,...,0,0,0,0,0,0,0,0,0,0.7
3,FOR04,FOR40,Bosco cancello,2022-06-16,1,y,45°17.4106',8°56.1672',494990.757,5015188.194,...,0,0,0,0,0,0,0,0,0,0.0
4,FOR05,FOR41,Bosco cancello,2022-06-16,1,y,45°17.4494',8°56.3050',495170.934,5015259.820,...,0,0,0,0,0,0,0,0,0,0.0

In [7]:
# Drop useless columns (We drop the columns of Copertura as well since currently these values don't contribute to our work yet. )
df_Field1_Useful = df_Field1.copy()
for column in df_Field1_Columns:
    if not ((column == 'ESU') or ("Piano Dominato" in column) or ("Piano Dominante" in column) or (column == 'Lat') or (column == 'Long') or (column == 'X_UTM (est)') or (column == 'Y_UTM (nord)')) or ('Copertura' in column):
        df_Field1_Useful = df_Field1_Useful.drop(columns = [column])
df_Field1_Useful

,ESU,Lat,Long,X_UTM (est),Y_UTM (nord),Piano Dominante - Robinia Pseudoacacia,Piano Dominante - Carpinus Betulus,Piano Dominante - Quercus Robur,Piano Dominante - Populus Canadensis,Piano Dominante - Alnus Glutinosa,...,Piano Dominato - Ulmus Minor,Piano Dominato - Acer Campestre,Piano Dominato - Alnus Glutinosa,Piano Dominato - Populus Tremula,Piano Dominato - Quercus Cerris,Piano Dominato - Popolus Nigra,Piano Dominato - Fraxinus Ornus,Piano Dominato - Castanea Sativa Miller,Piano Dominato - Ailanthus Altissima,Piano Dominato - Crataegus Monogyna
0,FOR01,45°34.0787',8°42.7080',477510.968,5046089.097,10,4,1,1,0,...,0,0,0,0,0,0,0,0,0,0
1,FOR02,45°34.2126',8°42.7501',477566.636,5046336.872,2,0,4,0,2,...,0,0,0,0,0,0,0,0,0,0
2,FOR03,45°34.1851',8°42.7864',477613.662,5046285.820,3,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,FOR04,45°17.4106',8°56.1672',494990.757,5015188.194,0,0,9,0,0,...,0,0,0,0,0,0,0,0,0,0
4,FOR05,45°17.4494',8°56.3050',495170.934,5015259.820,0,0,9,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,FOR78,45°39.4093',8°44.1476',479415.734,5055953.155,3,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
78,FOR79,45°39.3968',8°44.0236',479254.696,5055930.468,0,0,4,0,0,...,0,0,0,0,0,0,0,7,0,0
79,FOR80,45°39.8128',8°43.7756',478935.217,5056701.915,7,0,3,0,0,...,0,0,0,0,0,0,0,0,0,0
80,FOR81,45°39.9103',8°43.3556',478390.540,5056884.318,2,0,10,0,0,...,0,0,0,0,0,0,0,0,0,0
81,FOR82,45°39.8563',8°43.3840',478427.118,5056784.200,0,0,7,0,0,...,0,0,0,0,0,0,0,2,0,0

In [8]:
# Get the rows where there are no data of the quantities of the species
df_Field1_Columns_Truncated = df_Field1_Useful.columns
list_Row_toDrop = []
for row in range(0,df_Field1_Useful.shape[0]):
    temp_Check_toDrop = True
    for column in df_Field1_Columns_Truncated:
        if ("Piano Dominato" in column) or ("Piano Dominante" in column):
            if df_Field1_Useful.loc[df_Field1_Useful.iloc[row].name,column] != 0:
                temp_Check_toDrop = False
                break
    if temp_Check_toDrop:
        list_Row_toDrop.append(row)
list_Row_toDrop

[31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]

In [9]:
# Drop those empty rows! 
df_Field1_Valid = df_Field1_Useful.drop(index = df_Field1_Useful.index[list_Row_toDrop])
df_Field1_Valid

,ESU,Lat,Long,X_UTM (est),Y_UTM (nord),Piano Dominante - Robinia Pseudoacacia,Piano Dominante - Carpinus Betulus,Piano Dominante - Quercus Robur,Piano Dominante - Populus Canadensis,Piano Dominante - Alnus Glutinosa,...,Piano Dominato - Ulmus Minor,Piano Dominato - Acer Campestre,Piano Dominato - Alnus Glutinosa,Piano Dominato - Populus Tremula,Piano Dominato - Quercus Cerris,Piano Dominato - Popolus Nigra,Piano Dominato - Fraxinus Ornus,Piano Dominato - Castanea Sativa Miller,Piano Dominato - Ailanthus Altissima,Piano Dominato - Crataegus Monogyna
0,FOR01,45°34.0787',8°42.7080',477510.968,5046089.097,10,4,1,1,0,...,0,0,0,0,0,0,0,0,0,0
1,FOR02,45°34.2126',8°42.7501',477566.636,5046336.872,2,0,4,0,2,...,0,0,0,0,0,0,0,0,0,0
2,FOR03,45°34.1851',8°42.7864',477613.662,5046285.820,3,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,FOR04,45°17.4106',8°56.1672',494990.757,5015188.194,0,0,9,0,0,...,0,0,0,0,0,0,0,0,0,0
4,FOR05,45°17.4494',8°56.3050',495170.934,5015259.820,0,0,9,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,FOR78,45°39.4093',8°44.1476',479415.734,5055953.155,3,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
78,FOR79,45°39.3968',8°44.0236',479254.696,5055930.468,0,0,4,0,0,...,0,0,0,0,0,0,0,7,0,0
79,FOR80,45°39.8128',8°43.7756',478935.217,5056701.915,7,0,3,0,0,...,0,0,0,0,0,0,0,0,0,0
80,FOR81,45°39.9103',8°43.3556',478390.540,5056884.318,2,0,10,0,0,...,0,0,0,0,0,0,0,0,0,0
81,FOR82,45°39.8563',8°43.3840',478427.118,5056784.200,0,0,7,0,0,...,0,0,0,0,0,0,0,2,0,0

In [10]:
# Combine "Piano Dominante" and "Piano Dominato", merging the same species and keeping the unique species
list1_Spezie = []
for spezie in df_Field1_Valid.columns:
    if " - " in spezie:
        list1_Spezie.append(spezie)
list1_Spezie
list_Spezie_Dominato = []
list_Spezie_Dominante = []
for spezie in list1_Spezie:
    if "Dominato" in spezie:
        list_Spezie_Dominato.append(spezie.split(" - ")[1])
    elif "Dominante" in spezie:
        list_Spezie_Dominante.append(spezie.split(" - ")[1])
# Sum up the counts of the same plants in "Piano Dominante" and "Piano Dominato". 
df_Field1_Merge = df_Field1_Valid.copy()
for spezie_Dominante in list_Spezie_Dominante:
    # Set a check value in case that a plant only exists in "Piano Dominante"
    spezie_unique = True
    for spezie_Dominato in list_Spezie_Dominato: 
        if spezie_Dominante == spezie_Dominato:
            # Add up the counts if the plant exists in both "Piano Dominante" and "Piano Dominato"
            df_Field1_Merge[spezie_Dominante] = df_Field1_Merge[("Piano Dominante - " + spezie_Dominante)] + df_Field1_Merge[("Piano Dominato - " + spezie_Dominato)]
            # Drop the two columns! 
            df_Field1_Merge = df_Field1_Merge.drop(columns = [("Piano Dominante - " + spezie_Dominante),("Piano Dominato - " + spezie_Dominato)])
            spezie_unique = False
            break
    # If the plant only exists in "Piano Dominante", then no need to add any arithmetric operation! 
    if spezie_unique:
        df_Field1_Merge[spezie_Dominante] = df_Field1_Merge[("Piano Dominante - " + spezie_Dominante)]
        df_Field1_Merge = df_Field1_Merge.drop(columns = [("Piano Dominante - " + spezie_Dominante)])
# Now only the plants unique in "Piano Dominato" remain intact in the geodataframe. We simply rename their names! 
for column in df_Field1_Merge.columns: 
    if "Piano Dominato" in column:
        df_Field1_Merge = df_Field1_Merge.rename(columns={column: column.split(" - ")[1]})
# Finally check our columns of the final dataframe! 
df_Field1_Merge

,ESU,Lat,Long,X_UTM (est),Y_UTM (nord),Prunus Padus,Pronus Serotina,Ulmus Minor,Acer Campestre,Crataegus Monogyna,...,Quercus Cerris,Populus Cane scens,Pinus Rigida,Pinus Sylvestris,Castanea Sativa Miller,Betula Pendula,Ailanthus Altissima,Ulmus Minor Miller,Fraxinus Ornus,Quercus Pubescens
0,FOR01,45°34.0787',8°42.7080',477510.968,5046089.097,7,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,FOR02,45°34.2126',8°42.7501',477566.636,5046336.872,0,15,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,FOR03,45°34.1851',8°42.7864',477613.662,5046285.820,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,FOR04,45°17.4106',8°56.1672',494990.757,5015188.194,0,0,0,0,0,...,0,2,0,0,0,0,0,0,0,0
4,FOR05,45°17.4494',8°56.3050',495170.934,5015259.820,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,FOR78,45°39.4093',8°44.1476',479415.734,5055953.155,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
78,FOR79,45°39.3968',8°44.0236',479254.696,5055930.468,0,5,0,0,0,...,0,0,0,8,8,0,0,0,0,0
79,FOR80,45°39.8128',8°43.7756',478935.217,5056701.915,0,17,0,0,0,...,0,0,0,0,0,0,0,0,0,0
80,FOR81,45°39.9103',8°43.3556',478390.540,5056884.318,0,11,0,0,0,...,0,0,0,5,0,0,0,0,0,0
81,FOR82,45°39.8563',8°43.3840',478427.118,5056784.200,0,8,0,0,0,...,0,0,0,16,2,0,0,0,0,0

In [11]:
# Convert the latitude and longitude to the correct form
df_Field1_Merge['Lat'] = df_Field1_Merge['Lat'].str.split(r'°|\'', regex = True, expand = True).iloc[:,0].apply(pd.to_numeric) + df_Field1_Merge['Lat'].str.split(r'°|\'', regex = True, expand = True).iloc[:,1].apply(pd.to_numeric).apply(lambda row: row/60)
df_Field1_Merge['Long'] = df_Field1_Merge['Long'].str.split(r'°|\'', regex = True, expand = True).iloc[:,0].apply(pd.to_numeric) + df_Field1_Merge['Long'].str.split(r'°|\'', regex = True, expand = True).iloc[:,1].apply(pd.to_numeric).apply(lambda row: row/60)
df_Field1_Merge

,ESU,Lat,Long,X_UTM (est),Y_UTM (nord),Prunus Padus,Pronus Serotina,Ulmus Minor,Acer Campestre,Crataegus Monogyna,...,Quercus Cerris,Populus Cane scens,Pinus Rigida,Pinus Sylvestris,Castanea Sativa Miller,Betula Pendula,Ailanthus Altissima,Ulmus Minor Miller,Fraxinus Ornus,Quercus Pubescens
0,FOR01,45.567978,8.711800,477510.968,5046089.097,7,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,FOR02,45.570210,8.712502,477566.636,5046336.872,0,15,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,FOR03,45.569752,8.713107,477613.662,5046285.820,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,FOR04,45.290177,8.936120,494990.757,5015188.194,0,0,0,0,0,...,0,2,0,0,0,0,0,0,0,0
4,FOR05,45.290823,8.938417,495170.934,5015259.820,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,FOR78,45.656822,8.735793,479415.734,5055953.155,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
78,FOR79,45.656613,8.733727,479254.696,5055930.468,0,5,0,0,0,...,0,0,0,8,8,0,0,0,0,0
79,FOR80,45.663547,8.729593,478935.217,5056701.915,0,17,0,0,0,...,0,0,0,0,0,0,0,0,0,0
80,FOR81,45.665172,8.722593,478390.540,5056884.318,0,11,0,0,0,...,0,0,0,5,0,0,0,0,0,0
81,FOR82,45.664272,8.723067,478427.118,5056784.200,0,8,0,0,0,...,0,0,0,16,2,0,0,0,0,0

In [12]:
# Now we save only the geographical coordinates of all the valid plots! 
df_Field1_Merge[['ESU','Lat','Long']].rename(columns = {'ESU': 'Plot'}).to_csv(cwd_Field_Data1_CSV + "\\FieldData1 Valid LatLong.csv", index = False)
df_Field1_Merge[['ESU','X_UTM (est)','Y_UTM (nord)']].rename(columns = {'ESU': 'Plot', 'X_UTM (est)': 'UTM_X', 'Y_UTM (nord)': 'UTM_Y'}).to_csv(cwd_Field_Data1_CSV + "\\FieldData1 Valid UTM.csv", index = False)

### Now in this dataframe the names of all the species are columns. Here we want to transfer them into a row.

In [13]:
# Convert the species columns into rows, so that the new dataframe will only have 5 columns, where the fourth column will be the name of the species and the fifth column will be the quantity of that species
list1_FOR = []
list1_Lat = []
list1_Long = []
list1_UTM_X = []
list1_UTM_Y = []
list1_species = []
list1_quantity = []
for row in range(0,df_Field1_Merge.shape[0]):
    for column in df_Field1_Merge.columns:
        if not (column == 'ESU') and not (column == 'Lat') and not (column == 'Long') and not (column == 'X_UTM (est)') and not (column == 'Y_UTM (nord)'):
            if df_Field1_Merge.loc[df_Field1_Merge.iloc[row].name,column] != 0:
                list1_FOR.append(df_Field1_Merge.iloc[row,0])
                list1_Lat.append(df_Field1_Merge.iloc[row,1])
                list1_Long.append(df_Field1_Merge.iloc[row,2])
                list1_UTM_X.append(df_Field1_Merge.iloc[row,3])
                list1_UTM_Y.append(df_Field1_Merge.iloc[row,4])
                list1_species.append(column)
                list1_quantity.append(df_Field1_Merge.loc[df_Field1_Merge.iloc[row].name,column])
df_Field1_Converted = pd.DataFrame(
    data = {
        'Plot': list1_FOR,
        'Lat': list1_Lat,
        'Long': list1_Long,
        'UTM_X': list1_UTM_X,
        'UTM_Y': list1_UTM_Y,
        'Species': list1_species,
        'Quantity': list1_quantity
    }
)
df_Field1_Converted

,Plot,Lat,Long,UTM_X,UTM_Y,Species,Quantity
0,FOR01,45.567978,8.711800,477510.968,5046089.097,Prunus Padus,7
1,FOR01,45.567978,8.711800,477510.968,5046089.097,Robinia Pseudoacacia,12
2,FOR01,45.567978,8.711800,477510.968,5046089.097,Carpinus Betulus,13
3,FOR01,45.567978,8.711800,477510.968,5046089.097,Quercus Robur,1
4,FOR01,45.567978,8.711800,477510.968,5046089.097,Populus Canadensis,1
...,...,...,...,...,...,...,...
216,FOR81,45.665172,8.722593,478390.540,5056884.318,Pinus Sylvestris,5
217,FOR82,45.664272,8.723067,478427.118,5056784.200,Pronus Serotina,8
218,FOR82,45.664272,8.723067,478427.118,5056784.200,Quercus Robur,7
219,FOR82,45.664272,8.723067,478427.118,5056784.200,Pinus Sylvestris,16
220,FOR82,45.664272,8.723067,478427.118,5056784.200,Castanea Sativa Miller,2

In [14]:
# Save this dataframe into local csv file! 
df_Field1_Converted[['Plot','Lat','Long','Species','Quantity']].to_csv(cwd_Field_Data1_CSV + "\\FieldData1 Valid LatLong with Species.csv", index = False)
df_Field1_Converted[['Plot','UTM_X','UTM_Y','Species','Quantity']].to_csv(cwd_Field_Data1_CSV + "\\FieldData1 Valid UTM with Species.csv", index = False)
df_Field1_Converted[['Plot','Species','Quantity']].to_csv(cwd_Field_Data1_CSV + "\\FieldData1 Valid with Species.csv", index = False)

### Retrieve Typology

In [15]:
# Read typology first
df_Field1_Typo = df_Field1.copy()
df_Field1_Typo = df_Field1_Typo[['ESU','Tipologia Forestale castrovinci']]
# Keep only valid plots
df_Field1_Typo = pd.merge(df_Field1_Typo,df_Field1_Merge['ESU'],on='ESU',how='inner')
# Rename Columns
df_Field1_Typo.columns = ['Plot','Typology']
df_Field1_Typo

     Plot                       Typology
0   FOR01               QUERCO-CARPINETO
1   FOR02                PRUNUS SEROTINA
2   FOR03                PRUNUS SEROTINA
3   FOR04              QUERCETO XEROFILO
4   FOR05              QUERCETO XEROFILO
..    ...                            ...
58  FOR78                PRUNUS SEROTINA
59  FOR79         BOSCO MISTO LATIFOGLIE
60  FOR80         BOSCO MISTO LATIFOGLIE
61  FOR81  BOSCO MISTO LATIFOGLIE + pino
62  FOR82  BOSCO MISTO LATIFOGLIE + pino

[63 rows x 2 columns]

In [16]:
# Save!
df_Field1_Typo.to_csv(cwd_Field_Data1_CSV + "\\FieldData1 Valid Typology.csv", index = False)

### Merge Association

In [3]:
df_Field1_Asso = pd.read_csv(cwd_Field_Data1 + "\\ROI_30x30_rilievo_floristico_syntax_&_associazioni_forestali.csv")
df_Field1_Asso.tail()

,OBJECTID,ESU,Nome_ESU_C,Tipologia_,Syntaxon__,Associazio
58,45,FOR64,NaN,QUERCETO MESOXERICO,Querco-Ulmeto (intermedio),Oak
59,54,FOR73,NaN,QUERCETO MESOXERICO,Querco-Ulmeto (intermedio),Oak
60,44,FOR63,NaN,QUERCETO MOSOFILO,Querco-Ulmeto (intermedio),Mixed deciduous
61,6,FOR06,FOR42,QUERCO-CARPINETO,Querco-Ulmeto (+ umido),Oak_hornbeam_humid
62,43,FOR62,NaN,QUERCO-CARPINETO,Querceto_Prunus serotina,Oak

In [5]:
df_Field1_Asso = df_Field1_Asso.sort_values('ESU')
df_Field1_Asso

,OBJECTID,ESU,Nome_ESU_C,Tipologia_,Syntaxon__,Associazio
0,1,FOR01,FOR44,QUERCO-CARPINETO,Querco-Ulmeto (+ umido),Oak_hornbeam_humid
1,2,FOR02,FOR45,PRUNUS SEROTINA,Querceto_Prunus serotina,Prunus
2,3,FOR03,FOR46,PRUNUS SEROTINA,Querceto_Prunus serotina,Prunus
3,4,FOR04,FOR40,QUERCETO XEROFILO,Querceto_xerofilo_aperto,Oak_open_canopy
4,5,FOR05,FOR41,QUERCETO XEROFILO,Querceto_xerofilo_aperto,Oak_open_canopy
...,...,...,...,...,...,...
38,59,FOR78,NaN,PRUNUS SEROTINA,Castagno_Prunus_Robinia,Prunus
39,60,FOR79,NaN,BOSCO MISTO LATIFOGLIE,Castagno_Prunus_Robinia,Mixed deciduous
40,61,FOR80,NaN,BOSCO MISTO LATIFOGLIE,Castagno_Prunus_Robinia,Mixed deciduous
41,62,FOR81,NaN,BOSCO MISTO LATIFOGLIE + pino,Castagno_Prunus_Robinia,Mixed deciduous
42,63,FOR82,NaN,BOSCO MISTO LATIFOGLIE + pino,Castagno_Prunus_Robinia,Mixed deciduous

In [6]:
df_Field1_Asso = df_Field1_Asso.rename(columns = {'ESU': 'Plot', 'Associazio': "Association"})
df_Field1_Asso[['Plot','Association']].to_csv(cwd_Field_Data1_CSV + "\\FieldData1 Valid Association.csv", index = False)