# This notebook simply adds some buffer (5 x 10m for sentinel-2 and 5 x 30m for PRISMA) to our field data, in order for the R package biodivMapR

In [28]:
import geopandas as gpd

In [29]:
# Set some directories. Here we use absolute directories. 
cwd = 'c:\\Users\\m1865\\Desktop\\Ticino'
cwd_Field = cwd + '\\FieldData'
cwd_Field_DataMerged = cwd_Field + '\\Field Dataset Merged'
cwd_Field_DataMerged_Shapefiles = cwd_Field_DataMerged + "\\Shapefiles"
cwd_Field_DataMerged_Shapefiles_Buffer = cwd_Field_DataMerged + "\\Shapefiles Buffered"

In [30]:
gdf_Field_Valid_UTM = gpd.read_file(cwd_Field_DataMerged_Shapefiles + "\\FieldDataMerged Valid UTM.shp")
gdf_Field_Valid_UTM

     Plot          UTM_X         UTM_Y                        geometry
0   FOR01  477510.968000  5.046089e+06  POINT (477510.968 5046089.097)
1   FOR02  477566.636000  5.046337e+06  POINT (477566.636 5046336.872)
2   FOR03  477613.662000  5.046286e+06  POINT (477613.662 5046285.820)
3   FOR04  494990.757000  5.015188e+06  POINT (494990.757 5015188.194)
4   FOR05  495170.934000  5.015260e+06  POINT (495170.934 5015259.820)
..    ...            ...           ...                             ...
91     35  471037.151278  5.065596e+06  POINT (471037.151 5065595.838)
92     37  475302.661270  5.056976e+06  POINT (475302.661 5056976.158)
93     38  481019.609917  5.059270e+06  POINT (481019.610 5059270.183)
94     39  476404.258874  5.064511e+06  POINT (476404.259 5064510.592)
95     40  479556.832180  5.056529e+06  POINT (479556.832 5056529.385)

[96 rows x 4 columns]

In [31]:
# Add 5 x 10m square buffer for Sentinel 2. 
gdf_Field_Valid_UTM_Buffer50 = gdf_Field_Valid_UTM.copy()
gdf_Field_Valid_UTM_Buffer50['geometry'] = gdf_Field_Valid_UTM_Buffer50.geometry.buffer(25, cap_style = 3) # cap_style = 1 by default but for circular buffer
gdf_Field_Valid_UTM_Buffer50

,Plot,UTM_X,UTM_Y,geometry
0,FOR01,477510.968000,5.046089e+06,"POLYGON ((477535.968 5046114.097, 477535.968 5..."
1,FOR02,477566.636000,5.046337e+06,"POLYGON ((477591.636 5046361.872, 477591.636 5..."
2,FOR03,477613.662000,5.046286e+06,"POLYGON ((477638.662 5046310.820, 477638.662 5..."
3,FOR04,494990.757000,5.015188e+06,"POLYGON ((495015.757 5015213.194, 495015.757 5..."
4,FOR05,495170.934000,5.015260e+06,"POLYGON ((495195.934 5015284.820, 495195.934 5..."
...,...,...,...,...
91,35,471037.151278,5.065596e+06,"POLYGON ((471062.151 5065620.838, 471062.151 5..."
92,37,475302.661270,5.056976e+06,"POLYGON ((475327.661 5057001.158, 475327.661 5..."
93,38,481019.609917,5.059270e+06,"POLYGON ((481044.610 5059295.183, 481044.610 5..."
94,39,476404.258874,5.064511e+06,"POLYGON ((476429.259 5064535.592, 476429.259 5..."
95,40,479556.832180,5.056529e+06,"POLYGON ((479581.832 5056554.385, 479581.832 5..."

In [32]:
# Add 5 x 30m square buffer for PRISMA. 
gdf_Field_Valid_UTM_Buffer150 = gdf_Field_Valid_UTM.copy()
gdf_Field_Valid_UTM_Buffer150['geometry'] = gdf_Field_Valid_UTM_Buffer150.geometry.buffer(75, cap_style = 3)
gdf_Field_Valid_UTM_Buffer150

,Plot,UTM_X,UTM_Y,geometry
0,FOR01,477510.968000,5.046089e+06,"POLYGON ((477585.968 5046164.097, 477585.968 5..."
1,FOR02,477566.636000,5.046337e+06,"POLYGON ((477641.636 5046411.872, 477641.636 5..."
2,FOR03,477613.662000,5.046286e+06,"POLYGON ((477688.662 5046360.820, 477688.662 5..."
3,FOR04,494990.757000,5.015188e+06,"POLYGON ((495065.757 5015263.194, 495065.757 5..."
4,FOR05,495170.934000,5.015260e+06,"POLYGON ((495245.934 5015334.820, 495245.934 5..."
...,...,...,...,...
91,35,471037.151278,5.065596e+06,"POLYGON ((471112.151 5065670.838, 471112.151 5..."
92,37,475302.661270,5.056976e+06,"POLYGON ((475377.661 5057051.158, 475377.661 5..."
93,38,481019.609917,5.059270e+06,"POLYGON ((481094.610 5059345.183, 481094.610 5..."
94,39,476404.258874,5.064511e+06,"POLYGON ((476479.259 5064585.592, 476479.259 5..."
95,40,479556.832180,5.056529e+06,"POLYGON ((479631.832 5056604.385, 479631.832 5..."

In [33]:
# Add 10 x 10m square buffer for Sentinel 2. 
gdf_Field_Valid_UTM_Buffer100 = gdf_Field_Valid_UTM.copy()
gdf_Field_Valid_UTM_Buffer100['geometry'] = gdf_Field_Valid_UTM_Buffer100.geometry.buffer(50, cap_style = 3)
gdf_Field_Valid_UTM_Buffer100

,Plot,UTM_X,UTM_Y,geometry
0,FOR01,477510.968000,5.046089e+06,"POLYGON ((477560.968 5046139.097, 477560.968 5..."
1,FOR02,477566.636000,5.046337e+06,"POLYGON ((477616.636 5046386.872, 477616.636 5..."
2,FOR03,477613.662000,5.046286e+06,"POLYGON ((477663.662 5046335.820, 477663.662 5..."
3,FOR04,494990.757000,5.015188e+06,"POLYGON ((495040.757 5015238.194, 495040.757 5..."
4,FOR05,495170.934000,5.015260e+06,"POLYGON ((495220.934 5015309.820, 495220.934 5..."
...,...,...,...,...
91,35,471037.151278,5.065596e+06,"POLYGON ((471087.151 5065645.838, 471087.151 5..."
92,37,475302.661270,5.056976e+06,"POLYGON ((475352.661 5057026.158, 475352.661 5..."
93,38,481019.609917,5.059270e+06,"POLYGON ((481069.610 5059320.183, 481069.610 5..."
94,39,476404.258874,5.064511e+06,"POLYGON ((476454.259 5064560.592, 476454.259 5..."
95,40,479556.832180,5.056529e+06,"POLYGON ((479606.832 5056579.385, 479606.832 5..."

# Save these buffered geodataframes as shapefiles!

In [34]:
gdf_Field_Valid_UTM_Buffer50.to_file(cwd_Field_DataMerged_Shapefiles_Buffer + "\\FieldDataMerged Valid Buffer 50m UTM.shp")
gdf_Field_Valid_UTM_Buffer150.to_file(cwd_Field_DataMerged_Shapefiles_Buffer + "\\FieldDataMerged Valid Buffer 150m UTM.shp")
gdf_Field_Valid_UTM_Buffer100.to_file(cwd_Field_DataMerged_Shapefiles_Buffer + "\\FieldDataMerged Valid Buffer 100m UTM.shp")